name: consumer-action-1

on:
  push:
    branches:
      - main

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/comp-action-1
        id: action-1
      - run: |
          echo "${{ steps.action-1.outputs.random-number }}"
